name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: ethDemo
    runs-on: ubuntu-latest
    steps:
      - uses: shenyubo1982/ethdemo@master
        with:
          WAKATIME_API_KEY: ${{ 4de6d204-ba85-4117-be28-9023ffd25dea }}
